#pragma once

enum BlockActorRendererId {
    TR_DEFAULT_RENDERER,
    TR_CHEST_RENDERER,
    TR_SIGN_RENDERER,
    TR_MOBSPAWNER_RENDERER,
    TR_SKULL_RENDERER,
    TR_ENCHANTER_RENDERER,
    TR_PISTONARM_RENDERER,
    TR_ITEMFRAME_RENDERER,
    TR_MOVINGBLOCK_RENDERER,
    TR_CHALKBOARD_RENDERER,
    TR_BEACON_RENDERER,
    TR_ENDGATEWAY_RENDERER,
    TR_ENDERCHEST_RENDERER,
    TR_SHULKERBOX_RENDERER,
    TR_COMMANDBLOCK_RENDERER,
    TR_BED_RENDERER,
    TR_BANNER_RENDERER,
    TR_CONDUIT_RENDERER,
    TR_LECTERN_RENDERER,
    TR_BELL_RENDERER,
    TR_CAMPFIRE_RENDERER,
    TR_INFESTINGLEAVES_RENDERER = 100
};