#pragma once

enum class BlockActorType : int {
    Undefined,
    Furnace,
    Chest,
    NetherReactor,
    Sign,
    MobSpawner,
    Skull,
    FlowerPot,
    BrewingStand,
    EnchantingTable,
    DaylightDetector,
    Music,
    Comparator,
    Dispenser,
    Dropper,
    Hopper,
    Cauldron,
    ItemFrame,
    PistonArm,
    MovingBlock,
    Chalkboard,
    Beacon,
    EndPortal,
    EnderChest,
    EndGateway,
    ShulkerBox,
    CommandBlock,
    Bed,
    Banner,
    StructureBlock = 32,
    Jukebox,
    ChemistryTable,
    Conduit,
    JigsawBlock,
    Lectern,
    BlastFurnace,
    Smoker,
    Bell,
    Campfire,
    BarrelBlock,
    Beehive,
    InfestedLeaves = 50,
    InfestingLeaves = 51
};