// This file was automatically generated using tools/process_csv.py
// Generated on Wed Jul 08 2020 20:35:52 UTC

#include <Zenova/Hook.h>
#include "main.h"
#include "minecraft/block/VanillaBlockRegistry.h"
#include "minecraft/block/VanillaBlockStates.h"
#include "minecraft/block/VanillaBlockTypeRegistry.h"
#include "minecraft/block/BlockTypeRegistry.h"
#include "minecraft/item/VanillaItemTiers.h"
#include "minecraft/item/ItemRegistry.h"
#include "minecraft/block/BlockTypeRegistry.h"
#include "minecraft/world/WorldSystems.h"
#include "minecraft/item/Item.h"
#include "minecraft/item/VanillaItems.h"
#include "minecraft/actor/ActorType.h"
#include "minecraft/actor/ProjectileFactory.h"
#include "minecraft/actor/ActorFactory.h"
#include "minecraft/actor/Attributes.h"

Block** VanillaBlocks::mGrass = reinterpret_cast<Block**>(Zenova::Hook::SlideAddress(0x3050A98));
Block** VanillaBlocks::mDirt = reinterpret_cast<Block**>(Zenova::Hook::SlideAddress(0x3051770));
Block** VanillaBlocks::mCobblestone = reinterpret_cast<Block**>(Zenova::Hook::SlideAddress(0x3051570));
Block** VanillaBlocks::mSapling = reinterpret_cast<Block**>(Zenova::Hook::SlideAddress(0x30514D8));
Block** VanillaBlocks::mSand = reinterpret_cast<Block**>(Zenova::Hook::SlideAddress(0x3050B58));
Block** VanillaBlocks::mGravel = reinterpret_cast<Block**>(Zenova::Hook::SlideAddress(0x3050B60));
Block** VanillaBlocks::mLeaves = reinterpret_cast<Block**>(Zenova::Hook::SlideAddress(0x30515D0));
Block** VanillaBlocks::mCactus = reinterpret_cast<Block**>(Zenova::Hook::SlideAddress(0x3050B30));
Block** VanillaBlocks::mReeds = reinterpret_cast<Block**>(Zenova::Hook::SlideAddress(0x3050AA0));
Block** VanillaBlocks::mNetherrack = reinterpret_cast<Block**>(Zenova::Hook::SlideAddress(0x3051478));
Block** VanillaBlocks::mMycelium = reinterpret_cast<Block**>(Zenova::Hook::SlideAddress(0x3050B50));
Block** VanillaBlocks::mEndStone = reinterpret_cast<Block**>(Zenova::Hook::SlideAddress(0x3051470));
Block** VanillaBlocks::mCarrotCrop = reinterpret_cast<Block**>(Zenova::Hook::SlideAddress(0x30516A8));
Block** VanillaBlocks::mPotatoCrop = reinterpret_cast<Block**>(Zenova::Hook::SlideAddress(0x30516B0));
Block** VanillaBlocks::mLeaves2 = reinterpret_cast<Block**>(Zenova::Hook::SlideAddress(0x30510F0));
WeakPtr<BlockLegacy>* VanillaBlockTypes::mGrass = reinterpret_cast<WeakPtr<BlockLegacy>*>(Zenova::Hook::SlideAddress(0x3061468));
WeakPtr<BlockLegacy>* VanillaBlockTypes::mDirt = reinterpret_cast<WeakPtr<BlockLegacy>*>(Zenova::Hook::SlideAddress(0x3061470));
WeakPtr<BlockLegacy>* VanillaBlockTypes::mCobblestone = reinterpret_cast<WeakPtr<BlockLegacy>*>(Zenova::Hook::SlideAddress(0x3061478));
WeakPtr<BlockLegacy>* VanillaBlockTypes::mSand = reinterpret_cast<WeakPtr<BlockLegacy>*>(Zenova::Hook::SlideAddress(0x30614B8));
WeakPtr<BlockLegacy>* VanillaBlockTypes::mGravel = reinterpret_cast<WeakPtr<BlockLegacy>*>(Zenova::Hook::SlideAddress(0x30614C0));
WeakPtr<BlockLegacy>* VanillaBlockTypes::mLeaves = reinterpret_cast<WeakPtr<BlockLegacy>*>(Zenova::Hook::SlideAddress(0x30614E8));
WeakPtr<BlockLegacy>* VanillaBlockTypes::mMycelium = reinterpret_cast<WeakPtr<BlockLegacy>*>(Zenova::Hook::SlideAddress(0x30617F0));
WeakPtr<BlockLegacy>* VanillaBlockTypes::mLeaves2 = reinterpret_cast<WeakPtr<BlockLegacy>*>(Zenova::Hook::SlideAddress(0x30619E0));
WeakPtr<BlockLegacy>* VanillaBlockTypes::mTopSnow = reinterpret_cast<WeakPtr<BlockLegacy>*>(Zenova::Hook::SlideAddress(0x30616E0));
WeakPtr<BlockLegacy>* BedrockBlockTypes::mAir = reinterpret_cast<WeakPtr<BlockLegacy>*>(Zenova::Hook::SlideAddress(0x30613D0));
ItemState* VanillaStates::SaplingType = reinterpret_cast<ItemState*>(Zenova::Hook::SlideAddress(0x30633C0));
ItemState* VanillaStates::LiquidDepth = reinterpret_cast<ItemState*>(Zenova::Hook::SlideAddress(0x3062BA0));
WeakPtr<Item>* VanillaItems::mBucket = reinterpret_cast<WeakPtr<Item>*>(Zenova::Hook::SlideAddress(0x3060748));
WeakPtr<Item>* VanillaItems::mGoldIngot = reinterpret_cast<WeakPtr<Item>*>(Zenova::Hook::SlideAddress(0x3060548));
WeakPtr<Item>* VanillaItems::mIronIngot = reinterpret_cast<WeakPtr<Item>*>(Zenova::Hook::SlideAddress(0x3060540));
Item::Tier* VanillaItemTiers::WOOD = reinterpret_cast<Item::Tier*>(Zenova::Hook::SlideAddress(0x2A39988));
Item::Tier* VanillaItemTiers::STONE = reinterpret_cast<Item::Tier*>(Zenova::Hook::SlideAddress(0x2A39A20));
Item::Tier* VanillaItemTiers::IRON = reinterpret_cast<Item::Tier*>(Zenova::Hook::SlideAddress(0x2A39658));
Item::Tier* VanillaItemTiers::DIAMOND = reinterpret_cast<Item::Tier*>(Zenova::Hook::SlideAddress(0x2A39A38));
Item::Tier* VanillaItemTiers::GOLD = reinterpret_cast<Item::Tier*>(Zenova::Hook::SlideAddress(0x2A39A50));
std::vector<SharedPtr<Item>>* ItemRegistry::mItemRegistry = reinterpret_cast<std::vector<SharedPtr<Item>>*>(Zenova::Hook::SlideAddress(0x3060118));
short* ItemRegistry::mMaxItemID = reinterpret_cast<short*>(Zenova::Hook::SlideAddress(0x30507BC));
std::unordered_map<std::string, SharedPtr<BlockLegacy>>* BlockTypeRegistry::mBlockLookupMap = reinterpret_cast<std::unordered_map<std::string, SharedPtr<BlockLegacy>>*>(Zenova::Hook::SlideAddress(0x3061390));
bool* Item::mInCreativeGroup = reinterpret_cast<bool*>(Zenova::Hook::SlideAddress(0x30507BA));
std::vector<ItemInstance>* Item::mCreativeList = reinterpret_cast<std::vector<ItemInstance>*>(Zenova::Hook::SlideAddress(0x3060068));
std::vector<std::vector<ItemInstance>>* Item::mCreativeGroups = reinterpret_cast<std::vector<std::vector<ItemInstance>>*>(Zenova::Hook::SlideAddress(0x30600E8));
std::vector<CreativeGroupInfo>* Item::mCreativeGroupInfo = reinterpret_cast<std::vector<CreativeGroupInfo>*>(Zenova::Hook::SlideAddress(0x3060100));
bool* WorldSystems::mInitialized = reinterpret_cast<bool*>(Zenova::Hook::SlideAddress(0x30507BE));
std::unordered_map<ActorType, ActorMapping>* ENTITY_TYPE_MAP = reinterpret_cast<std::unordered_map<ActorType, ActorMapping>*>(Zenova::Hook::SlideAddress(0x305C590));
std::unordered_map<std::string, std::function<std::unique_ptr<OnHitSubcomponent>()>>* ProjectileFactory::mSubcomponentMap = reinterpret_cast<std::unordered_map<std::string, std::function<std::unique_ptr<OnHitSubcomponent>()>>*>(Zenova::Hook::SlideAddress(0x305DD20));
std::unordered_map<std::string, ActorFactoryData>* _factoryFunctions = reinterpret_cast<std::unordered_map<std::string, ActorFactoryData>*>(Zenova::Hook::SlideAddress(0x305C460));
Attribute* SharedAttributes::HEALTH = reinterpret_cast<Attribute*>(Zenova::Hook::SlideAddress(0x305DDA0));

extern "C" {
	void* __0Item__QEAA_AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__F_Z_ptr;
	void* __0BlockPlanterItem__QEAA_AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__HAEBVBlock___N_Z_ptr;
	void* __0DiggerItem__IEAA_AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__HHAEBVTier_Item__AEBV_$vector_PEBVBlock__V_$allocator_PEBVBlock___std___2__Z_ptr;
	void* __0BlockItem__QEAA_AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__H_Z_ptr;
	void* __0BucketItem__QEAA_AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__H_Z_ptr;
	void* _beginCreativeGroup_Item__SAXAEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__PEAV1_FPEBVCompoundTag___Z_ptr;
	void* _addCreativeItem_Item__SAXPEAV1_F_Z_ptr;
	void* _addCreativeItem_Item__SAXAEBVBlock___Z_ptr;
	void* _getTextureItem_Item__SAAEBVTextureAtlasItem__AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___Z_ptr;
	void* _getIconTextureUVSet_Item__SAAEBUTextureUVCoordinateSet__AEBVTextureAtlasItem__HH_Z_ptr;
	void* _getTextureUVCoordinateSet_Item__SA_AUTextureUVCoordinateSet__AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__H_Z_ptr;
	void* _getCommandName_Item__QEBAAEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__XZ_ptr;
	void* __helpChangeInventoryItemInPlace_Item__QEBAXAEAVActor__AEAVItemStack__1W4ItemAcquisitionMethod___Z_ptr;
	void* __1ItemStackBase__UEAA_XZ_ptr;
	void* __0ItemStackBase__IEAA_XZ_ptr;
	void* __0ItemStackBase__IEAA_AEBVItem__HH_Z_ptr;
	void* __0ItemStackBase__IEAA_AEBVBlockLegacy__H_Z_ptr;
	void* __0ItemStackBase__IEAA_AEBVBlock__HPEBVCompoundTag___Z_ptr;
	void* __0ItemStackBase__IEAA_AEBV0__Z_ptr;
	void* __4ItemStackBase__IEAAAEAV0_AEBV0__Z_ptr;
	void* __0ItemStack__QEAA_XZ_ptr;
	void* __0ItemStack__QEAA_AEBVItem__H_Z_ptr;
	void* __0ItemStack__QEAA_AEBVBlockLegacy__H_Z_ptr;
	void* __0ItemInstance__QEAA_XZ_ptr;
	void* __0ItemInstance__QEAA_AEBVItem__HH_Z_ptr;
	void* __0ItemInstance__QEAA_AEBVBlockLegacy__H_Z_ptr;
	void* __0ItemInstance__QEAA_AEBVBlock__HPEBVCompoundTag___Z_ptr;
	void* __0ItemInstance__QEAA_AEBV0__Z_ptr;
	void* _set_ItemStackBase__QEAAXH_Z_ptr;
	void* _getItem_ItemStackBase__QEBAPEBVItem__XZ_ptr;
	void* _getAuxValue_ItemStackBase__QEBAFXZ_ptr;
	void* _matchesItem_ItemStackBase__QEBA_NAEBV1__Z_ptr;
	void* _addToTickingQueue_BlockSource__QEAAXAEBVBlockPos__AEBVBlock__HH_Z_ptr;
	void* _getBlock_BlockSource__QEBAAEBVBlock__AEBVBlockPos___Z_ptr;
	void* _getExtraBlock_BlockSource__QEBAAEBVBlock__AEBVBlockPos___Z_ptr;
	void* _getLiquidBlock_BlockSource__QEBAAEBVBlock__AEBVBlockPos___Z_ptr;
	void* _setBlock_BlockSource__QEAA_NAEBVBlockPos__AEBVBlock__HPEBUActorBlockSyncMessage___Z_ptr;
	void* _setExtraBlock_BlockSource__QEAA_NAEBVBlockPos__AEBVBlock__H_Z_ptr;
	void* _removeBlock_BlockSource__QEAA_NAEBVBlockPos___Z_ptr;
	void* _checkBlockPermissions_BlockSource__QEAA_NAEAVActor__AEBVBlockPos__EAEBVItemStack___N_Z_ptr;
	void* _getLegacyBlock_Block__QEBAAEBVBlockLegacy__XZ_ptr;
	void* __0BlockLegacy__QEAA_AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__HAEBVMaterial___Z_ptr;
	void* _getBlockItemId_BlockLegacy__QEBAFXZ_ptr;
	void* _tryGetStateFromLegacyData_BlockLegacy__QEBAPEBVBlock__G_Z_ptr;
	void* _popResource_BlockLegacy__QEBAPEAVItemActor__AEAVBlockSource__AEBVBlockPos__AEBVItemInstance___Z_ptr;
	void* _getDefaultState_BlockLegacy__QEBAAEAVBlock__XZ_ptr;
	void* _registerItem_ItemRegistry__SAXV_$SharedPtr_VItem_____Z_ptr;
	void* _getItem_ItemRegistry__SA_AV_$WeakPtr_VItem____F_Z_ptr;
	void* _lookupByName_ItemRegistry__SA_AV_$WeakPtr_VItem____AEAH0AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___Z_ptr;
	void* _lookupByName_ItemRegistry__SA_AV_$WeakPtr_VItem____AEAHAEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___Z_ptr;
	void* _registerItems_VanillaItems__SAX_N_Z_ptr;
	void* _initCreativeCategories_VanillaItems__SAXXZ_ptr;
	void* _initCreativeItemsCallback_VanillaItems__SAXPEAVActorInfoRegistry__PEAVBlockDefinitionGroup___N_Z_ptr;
	void* _initClientData_VanillaItems__SAXXZ_ptr;
	void* __genRandInt32_Random_Core__AEAAIXZ_ptr;
	void* _nextFloat_Random__QEAAMXZ_ptr;
	void* __0Throwable__QEAA_PEAVActorDefinitionGroup__AEBUActorDefinitionIdentifier___Z_ptr;
	void* _getSelectedItem_Player__QEBAAEBVItemStack__XZ_ptr;
	void* _causeFoodExhaustion_Player__QEAAXM_Z_ptr;
	void* _getEnchantLevel_EnchantUtils__SAHW4Type_Enchant__AEBVItemStackBase___Z_ptr;
	void* _hasEnchant_EnchantUtils__SA_NW4Type_Enchant__AEBVItemStackBase___Z_ptr;
	void* _toLower_Util__YA_AV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEBV23__Z_ptr;
	void* _toUpper_Util__YA_AV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEBV23__Z_ptr;
	void* _u64FromString_Util__YA_KAEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___Z_ptr;
	void* _registerBlockGraphics_BlockGraphics__SAAEAV1_AEAV_$vector_VValue_Json__V_$allocator_VValue_Json___std___std__AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__3_W4BlockShape___Z_ptr;
	void* _registerLooseBlockGraphics_BlockGraphics__SAXAEAV_$vector_VValue_Json__V_$allocator_VValue_Json___std___std__AEBVBlockPalette___Z_ptr;
	void* _getMaterial_Material__SAAEBV1_W4MaterialType___Z_ptr;
	void* _init_WorldSystems__SAXPEAVResourcePackManager___Z_ptr;
	void* _shutdown_VanillaWorldSystems__YAXXZ_ptr;
	void* _registerBlocks_VanillaBlockTypes__YAXXZ_ptr;
	void* _lookupByName_BlockTypeRegistry__SA_AV_$WeakPtr_VBlockLegacy____AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___Z_ptr;
	void* __1BlockLegacy__UEAA_XZ_ptr;
	void* __1Actor__UEAA_XZ_ptr;
	void* _registerBlocks_BlockDefinitionGroup__QEAAXXZ_ptr;
	void* _spawnProjectile_Spawner__QEAAPEAVActor__AEAVBlockSource__AEBUActorDefinitionIdentifier__PEAV2_AEBVVec3__3_Z_ptr;
	void* _spawnMob_Spawner__QEAAPEAVMob__AEAVBlockSource__AEBUActorDefinitionIdentifier__PEAVActor__AEBVVec3___N44_Z_ptr;
	void* _spawnItem_Spawner__QEAAPEAVItemActor__AEAVBlockSource__AEBVItemStack__PEAVActor__AEBVVec3__H_Z_ptr;
	void* __0ActorDefinitionIdentifier__QEAA_W4ActorType___Z_ptr;
	void* __initialize_ActorDefinitionIdentifier__AEAAXXZ_ptr;
	void* __extractIdentifier_ActorDefinitionIdentifier__CAXAEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEAU1__Z_ptr;
	void* _computeHash_HashedString__SA_KPEBD_Z_ptr;
	void* _initFactory_ProjectileFactory__SAXXZ_ptr;
	void* _EntityCanonicalName__YAAEBVHashedString__W4ActorType___Z_ptr;
	void* _EntityTypeToString__YA_AV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__W4ActorType__W4ActorTypeNamespaceRules___Z_ptr;
	void* _initializeEntityRenderers_ActorRenderDispatcher__QEAAXAEAVGeometryGroup__AEAVTextureGroup_mce__AEAVBlockTessellator__AEBVActorResourceDefinitionGroup__AEBVSemVersion___Z_ptr;
	void* _getRenderer_ActorRenderDispatcher__QEBAPEAVActorRenderer__AEBVHashedString___Z_ptr;
	void* _getDataDrivenRenderer_ActorRenderDispatcher__QEBAPEAVDataDrivenRenderer__AEBVHashedString___Z_ptr;
	void* _registerActorInfo_ActorInfoRegistry__QEAAXAEBUActorInfo___Z_ptr;
	void* _setDefinitionGroup_ActorFactory__QEAAXPEAVActorDefinitionGroup___Z_ptr;
	void* _broadcastLevelEvent_Level__QEAAXW4LevelEvent__AEBVVec3__HPEAVPlayer___Z_ptr;
	void* _broadcastSoundEvent_Level__QEAAXAEAVBlockSource__W4LevelSoundEvent__AEBVVec3__HAEBUActorDefinitionIdentifier___N4_Z_ptr;
	void* _broadcastDimensionEvent_Level__QEAAXAEAVBlockSource__W4LevelEvent__AEBVVec3__HPEAVPlayer___Z_ptr;
	void* _registerVanillaActorData_VanillaActors__YAXXZ_ptr;
	void* _GetActorDataRegistry__YAAEAV_$unordered_map_V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__UActorFactoryData__U_$hash_V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___2_U_$equal_to_V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___2_V_$allocator_U_$pair_$$CBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__UActorFactoryData___std___2__std__XZ_ptr;
	void* _putShort_CompoundTag__QEAAAEAFV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__F_Z_ptr;
	void* _getShort_CompoundTag__QEBAFV_$basic_string_span_$$CBD$0_0_gsl___Z_ptr;
	void* _onItemSpawnedActor_ItemEventCoordinator__QEAAXAEBVItemInstance__AEBVActor___Z_ptr;
	void* _sendActorAcquiredItem_ActorEventCoordinator__QEAAXAEAVActor__AEBVItemInstance__IW4ItemAcquisitionMethod__PEAV2__Z_ptr;
	void* _sendActorUseItem_ActorEventCoordinator__QEAAXAEAVActor__AEBVItemInstance__W4ItemUseMethod___Z_ptr;
	void* _createSpawnedEntity_ActorFactory__QEAA_AV_$unique_ptr_VActor__U_$default_delete_VActor___std___std__AEBUActorDefinitionIdentifier__PEAVActor__AEBVVec3__AEBVVec2___Z_ptr;
	void* _createTransformedEntity_ActorFactory__QEAA_AV_$unique_ptr_VActor__U_$default_delete_VActor___std___std__AEBUActorDefinitionIdentifier__PEAVActor___Z_ptr;
	void* __tick_LiquidBlockDynamic__AEBA_NAEAVBlockSource__AEBVBlockPos__AEAVRandom___N_Z_ptr;
	void* _switchBlock_BlockPalette__QEBAAEBVBlock__AEBV2_AEBVBlockLegacy___Z_ptr;
	void* _isInstanceOf_ActorClassTree__SA_NAEBVActor__W4ActorType___Z_ptr;
	void* _getVariant_Actor__QEBAHXZ_ptr;
	void* _setVariant_Actor__QEAAXH_Z_ptr;
	void* _isPersistent_Actor__QEBA_NXZ_ptr;
	void* _setPersistent_Actor__QEAAXXZ_ptr;
	void* _getStatusFlag_Actor__QEBA_NW4ActorFlags___Z_ptr;
	void* _setStatusFlag_Actor__QEAA_NW4ActorFlags___N_Z_ptr;
	void* _addEffect_Actor__QEAAXAEBVMobEffectInstance___Z_ptr;
	void* __0MobEffectInstance__QEAA_IHHHHH_N00_Z_ptr;
	void* _getByName_MobEffect__SAPEAV1_AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___Z_ptr;
	void* _get_I18n__SA_AV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEBV23__Z_ptr;
	void* __takeLiquid_BucketItem__QEBA_NAEAVItemStack__AEAVActor__AEBVBlockPos___Z_ptr;
	void* _ejectItem_DispenserBlock__SAXAEAVBlockSource__AEBVVec3__EAEBVItemStack___Z_ptr;
	void* __0ItemSpriteRenderer__QEAA_AEAVTextureGroup_mce__PEAVItem___N_Z_ptr;
	void* __1ItemSpriteRenderer__UEAA_XZ_ptr;
	void* _onAppSuspended_ItemSpriteRenderer__UEAAXXZ_ptr;
	void* __renderQuad_ItemSpriteRenderer__QEAAXAEAVBaseActorRenderContext__AEAVActor__AEAVMesh_mce__AEBVVec3__MM_Z_ptr;
	void* __buildQuad_ItemSpriteRenderer__QEAAXAEAVBaseActorRenderContext__AEAVActor__AEAVMesh_mce___Z_ptr;
	void* __1Mesh_mce__QEAA_XZ_ptr;
	void* __0Mesh_mce__QEAA_XZ_ptr;
	void* _reset_Mesh_mce__QEAAXXZ_ptr;
	void* _isValid_Mesh_mce__QEBA_NXZ_ptr;
	void* _init_Recipes__QEAAXAEAVResourcePackManager___Z_ptr;
	void* _addFurnaceRecipeAuxData_Recipes__QEAAXAEBVItemInstance__0AEBV_$vector_VHashString_Util__V_$allocator_VHashString_Util___std___std___Z_ptr;
	void* _addShapedRecipe_Recipes__QEAAXV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEBVItemInstance__AEBV23_22AEBV_$vector_VType_Recipes__V_$allocator_VType_Recipes___std___3_AEBV_$vector_VHashString_Util__V_$allocator_VHashString_Util___std___3_HV_$function_$$A6A_AV_$unique_ptr_VShapedRecipe__U_$default_delete_VShapedRecipe___std___std__V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__2_HHAEBV_$vector_VRecipeIngredient__V_$allocator_VRecipeIngredient___std___2_AEBV_$vector_VItemInstance__V_$allocator_VItemInstance___std___2_VHashString_Util___Z_3__Z_ptr;
	void* _addShapedRecipe_Recipes__QEAAXV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEBVItemInstance__AEBV23_2AEBV_$vector_VType_Recipes__V_$allocator_VType_Recipes___std___3_AEBV_$vector_VHashString_Util__V_$allocator_VHashString_Util___std___3_HV_$function_$$A6A_AV_$unique_ptr_VShapedRecipe__U_$default_delete_VShapedRecipe___std___std__V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__2_HHAEBV_$vector_VRecipeIngredient__V_$allocator_VRecipeIngredient___std___2_AEBV_$vector_VItemInstance__V_$allocator_VItemInstance___std___2_VHashString_Util___Z_3__Z_ptr;
	void* _addShapedRecipe_Recipes__QEAAXV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEBVItemInstance__AEBV23_AEBV_$vector_VType_Recipes__V_$allocator_VType_Recipes___std___3_AEBV_$vector_VHashString_Util__V_$allocator_VHashString_Util___std___3_HV_$function_$$A6A_AV_$unique_ptr_VShapedRecipe__U_$default_delete_VShapedRecipe___std___std__V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__2_HHAEBV_$vector_VRecipeIngredient__V_$allocator_VRecipeIngredient___std___2_AEBV_$vector_VItemInstance__V_$allocator_VItemInstance___std___2_VHashString_Util___Z_3__Z_ptr;
	void* _addShapedRecipe_Recipes__QEAAXV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEBVItemInstance__AEBV_$vector_V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__V_$allocator_V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___2__3_AEBV_$vector_VType_Recipes__V_$allocator_VType_Recipes___std___3_AEBV_$vector_VHashString_Util__V_$allocator_VHashString_Util___std___3_HV_$function_$$A6A_AV_$unique_ptr_VShapedRecipe__U_$default_delete_VShapedRecipe___std___std__V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__2_HHAEBV_$vector_VRecipeIngredient__V_$allocator_VRecipeIngredient___std___2_AEBV_$vector_VItemInstance__V_$allocator_VItemInstance___std___2_VHashString_Util___Z_3__Z_ptr;
	void* _addShapedRecipe_Recipes__QEAAXV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEBV_$vector_VItemInstance__V_$allocator_VItemInstance___std___3_AEBV_$vector_V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__V_$allocator_V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___2__3_AEBV_$vector_VType_Recipes__V_$allocator_VType_Recipes___std___3_AEBV_$vector_VHashString_Util__V_$allocator_VHashString_Util___std___3_HV_$function_$$A6A_AV_$unique_ptr_VShapedRecipe__U_$default_delete_VShapedRecipe___std___std__V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__2_HHAEBV_$vector_VRecipeIngredient__V_$allocator_VRecipeIngredient___std___2_AEBV_$vector_VItemInstance__V_$allocator_VItemInstance___std___2_VHashString_Util___Z_3__Z_ptr;
	void* Item_vtable;
	void* DiggerItem_vtable;
	void* BlockPlanterItem_vtable;
	void* BlockItem_vtable;
	void* BucketItem_vtable;
	void* BlockLegacy_vtable;
	void* LiquidBlock_vtable;
	void* HeavyBlock_vtable;
	void* ItemInstance_vtable;
	void* ItemStack_vtable;
	void* Actor_vtable;
	void* Mob_vtable;
	void* Player_vtable;
	void* Monster_vtable;
	void* Slime_vtable;
	void* Throwable_vtable;
	void* Container_vtable;
	void* Level_vtable;
	void* ItemSpriteRenderer_vtable;
}

void InitBedrockPointers() {
	__0Item__QEAA_AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__F_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x15614E0));
	__0BlockPlanterItem__QEAA_AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__HAEBVBlock___N_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1515440));
	__0DiggerItem__IEAA_AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__HHAEBVTier_Item__AEBV_$vector_PEBVBlock__V_$allocator_PEBVBlock___std___2__Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1547810));
	__0BlockItem__QEAA_AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__H_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1514950));
	__0BucketItem__QEAA_AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__H_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x15171C0));
	_beginCreativeGroup_Item__SAXAEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__PEAV1_FPEBVCompoundTag___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1560AB0));
	_addCreativeItem_Item__SAXPEAV1_F_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1560C90));
	_addCreativeItem_Item__SAXAEBVBlock___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1560BD0));
	_getTextureItem_Item__SAAEBVTextureAtlasItem__AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x15656C0));
	_getIconTextureUVSet_Item__SAAEBUTextureUVCoordinateSet__AEBVTextureAtlasItem__HH_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1565640));
	_getTextureUVCoordinateSet_Item__SA_AUTextureUVCoordinateSet__AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__H_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x15654E0));
	_getCommandName_Item__QEBAAEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__XZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1565810));
	__helpChangeInventoryItemInPlace_Item__QEBAXAEAVActor__AEAVItemStack__1W4ItemAcquisitionMethod___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1561210));
	__1ItemStackBase__UEAA_XZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x010B600));
	__0ItemStackBase__IEAA_XZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x156E290));
	__0ItemStackBase__IEAA_AEBVItem__HH_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x156E6C0));
	__0ItemStackBase__IEAA_AEBVBlockLegacy__H_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x156E360));
	__0ItemStackBase__IEAA_AEBVBlock__HPEBVCompoundTag___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x156E3F0));
	__0ItemStackBase__IEAA_AEBV0__Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x156E7D0));
	__4ItemStackBase__IEAAAEAV0_AEBV0__Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1571D80));
	__0ItemStack__QEAA_XZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x156D210));
	__0ItemStack__QEAA_AEBVItem__H_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x156D270));
	__0ItemStack__QEAA_AEBVBlockLegacy__H_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x156D240));
	__0ItemInstance__QEAA_XZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1568AD0));
	__0ItemInstance__QEAA_AEBVItem__HH_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1568C00));
	__0ItemInstance__QEAA_AEBVBlockLegacy__H_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1568B40));
	__0ItemInstance__QEAA_AEBVBlock__HPEBVCompoundTag___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1568B70));
	__0ItemInstance__QEAA_AEBV0__Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1568C30));
	_set_ItemStackBase__QEAAXH_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x156EF70));
	_getItem_ItemStackBase__QEBAPEBVItem__XZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x01B9250));
	_getAuxValue_ItemStackBase__QEBAFXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x15700E0));
	_matchesItem_ItemStackBase__QEBA_NAEBV1__Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1571BF0));
	_addToTickingQueue_BlockSource__QEAAXAEBVBlockPos__AEBVBlock__HH_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1778AB0));
	_getBlock_BlockSource__QEBAAEBVBlock__AEBVBlockPos___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1779710));
	_getExtraBlock_BlockSource__QEBAAEBVBlock__AEBVBlockPos___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1779E90));
	_getLiquidBlock_BlockSource__QEBAAEBVBlock__AEBVBlockPos___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1779E20));
	_setBlock_BlockSource__QEAA_NAEBVBlockPos__AEBVBlock__HPEBUActorBlockSyncMessage___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x17797E0));
	_setExtraBlock_BlockSource__QEAA_NAEBVBlockPos__AEBVBlock__H_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1779BD0));
	_removeBlock_BlockSource__QEAA_NAEBVBlockPos___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x177ADB0));
	_checkBlockPermissions_BlockSource__QEAA_NAEAVActor__AEBVBlockPos__EAEBVItemStack___N_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1778690));
	_getLegacyBlock_Block__QEBAAEBVBlockLegacy__XZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x00E9920));
	__0BlockLegacy__QEAA_AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__HAEBVMaterial___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x164EC50));
	_getBlockItemId_BlockLegacy__QEBAFXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1651D90));
	_tryGetStateFromLegacyData_BlockLegacy__QEBAPEBVBlock__G_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x164F4B0));
	_popResource_BlockLegacy__QEBAPEAVItemActor__AEAVBlockSource__AEBVBlockPos__AEBVItemInstance___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1650520));
	_getDefaultState_BlockLegacy__QEBAAEAVBlock__XZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1651D80));
	_registerItem_ItemRegistry__SAXV_$SharedPtr_VItem_____Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x15692F0));
	_getItem_ItemRegistry__SA_AV_$WeakPtr_VItem____F_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1569180));
	_lookupByName_ItemRegistry__SA_AV_$WeakPtr_VItem____AEAH0AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x156B410));
	_lookupByName_ItemRegistry__SA_AV_$WeakPtr_VItem____AEAHAEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x156AA50));
	_registerItems_VanillaItems__SAX_N_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1594D20));
	_initCreativeCategories_VanillaItems__SAXXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x15A3320));
	_initCreativeItemsCallback_VanillaItems__SAXPEAVActorInfoRegistry__PEAVBlockDefinitionGroup___N_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x15A45F0));
	_initClientData_VanillaItems__SAXXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x15A01D0));
	__genRandInt32_Random_Core__AEAAIXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x01AC370));
	_nextFloat_Random__QEAAMXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x0620D10));
	__0Throwable__QEAA_PEAVActorDefinitionGroup__AEBUActorDefinitionIdentifier___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x146CCF0));
	_getSelectedItem_Player__QEBAAEBVItemStack__XZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1459C30));
	_causeFoodExhaustion_Player__QEAAXM_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x145BD20));
	_getEnchantLevel_EnchantUtils__SAHW4Type_Enchant__AEBVItemStackBase___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x15506F0));
	_hasEnchant_EnchantUtils__SA_NW4Type_Enchant__AEBVItemStackBase___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x15507A0));
	_toLower_Util__YA_AV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEBV23__Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x0E52DA0));
	_toUpper_Util__YA_AV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEBV23__Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x0E52E40));
	_u64FromString_Util__YA_KAEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x0E53800));
	_registerBlockGraphics_BlockGraphics__SAAEAV1_AEAV_$vector_VValue_Json__V_$allocator_VValue_Json___std___std__AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__3_W4BlockShape___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x099C240));
	_registerLooseBlockGraphics_BlockGraphics__SAXAEAV_$vector_VValue_Json__V_$allocator_VValue_Json___std___std__AEBVBlockPalette___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x099CA10));
	_getMaterial_Material__SAAEBV1_W4MaterialType___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1892CB0));
	_init_WorldSystems__SAXPEAVResourcePackManager___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x19151A0));
	_shutdown_VanillaWorldSystems__YAXXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1B53370));
	_registerBlocks_VanillaBlockTypes__YAXXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x16E0AB0));
	_lookupByName_BlockTypeRegistry__SA_AV_$WeakPtr_VBlockLegacy____AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x16D9640));
	__1BlockLegacy__UEAA_XZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x164F200));
	__1Actor__UEAA_XZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x125CAF0));
	_registerBlocks_BlockDefinitionGroup__QEAAXXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x169EDC0));
	_spawnProjectile_Spawner__QEAAPEAVActor__AEAVBlockSource__AEBUActorDefinitionIdentifier__PEAV2_AEBVVec3__3_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x18AC210));
	_spawnMob_Spawner__QEAAPEAVMob__AEAVBlockSource__AEBUActorDefinitionIdentifier__PEAVActor__AEBVVec3___N44_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x18ABF10));
	_spawnItem_Spawner__QEAAPEAVItemActor__AEAVBlockSource__AEBVItemStack__PEAVActor__AEBVVec3__H_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x18AC0A0));
	__0ActorDefinitionIdentifier__QEAA_W4ActorType___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x12ECB50));
	__initialize_ActorDefinitionIdentifier__AEAAXXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x12ECEA0));
	__extractIdentifier_ActorDefinitionIdentifier__CAXAEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEAU1__Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x12EC620));
	_computeHash_HashedString__SA_KPEBD_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x0E42550));
	_initFactory_ProjectileFactory__SAXXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x146AD60));
	_EntityCanonicalName__YAAEBVHashedString__W4ActorType___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1305C00));
	_EntityTypeToString__YA_AV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__W4ActorType__W4ActorTypeNamespaceRules___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x13057E0));
	_initializeEntityRenderers_ActorRenderDispatcher__QEAAXAEAVGeometryGroup__AEAVTextureGroup_mce__AEAVBlockTessellator__AEBVActorResourceDefinitionGroup__AEBVSemVersion___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x093D2A0));
	_getRenderer_ActorRenderDispatcher__QEBAPEAVActorRenderer__AEBVHashedString___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x09410E0));
	_getDataDrivenRenderer_ActorRenderDispatcher__QEBAPEAVDataDrivenRenderer__AEBVHashedString___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x09410E0));
	_registerActorInfo_ActorInfoRegistry__QEAAXAEBUActorInfo___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x12F8840));
	_setDefinitionGroup_ActorFactory__QEAAXPEAVActorDefinitionGroup___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x12ED4C0));
	_broadcastLevelEvent_Level__QEAAXW4LevelEvent__AEBVVec3__HPEAVPlayer___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x17D4C40));
	_broadcastSoundEvent_Level__QEAAXAEAVBlockSource__W4LevelSoundEvent__AEBVVec3__HAEBUActorDefinitionIdentifier___N4_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x17D5070));
	_broadcastDimensionEvent_Level__QEAAXAEAVBlockSource__W4LevelEvent__AEBVVec3__HPEAVPlayer___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x17D5320));
	_registerVanillaActorData_VanillaActors__YAXXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x146F630));
	_GetActorDataRegistry__YAAEAV_$unordered_map_V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__UActorFactoryData__U_$hash_V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___2_U_$equal_to_V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___2_V_$allocator_U_$pair_$$CBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__UActorFactoryData___std___2__std__XZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x12FF7C0));
	_putShort_CompoundTag__QEAAAEAFV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__F_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x0FDC270));
	_getShort_CompoundTag__QEBAFV_$basic_string_span_$$CBD$0_0_gsl___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x0FDCC50));
	_onItemSpawnedActor_ItemEventCoordinator__QEAAXAEBVItemInstance__AEBVActor___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x14E8430));
	_sendActorAcquiredItem_ActorEventCoordinator__QEAAXAEAVActor__AEBVItemInstance__IW4ItemAcquisitionMethod__PEAV2__Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x14E6420));
	_sendActorUseItem_ActorEventCoordinator__QEAAXAEAVActor__AEBVItemInstance__W4ItemUseMethod___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x14E63C0));
	_createSpawnedEntity_ActorFactory__QEAA_AV_$unique_ptr_VActor__U_$default_delete_VActor___std___std__AEBUActorDefinitionIdentifier__PEAVActor__AEBVVec3__AEBVVec2___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x12EF9D0));
	_createTransformedEntity_ActorFactory__QEAA_AV_$unique_ptr_VActor__U_$default_delete_VActor___std___std__AEBUActorDefinitionIdentifier__PEAVActor___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x12F0110));
	__tick_LiquidBlockDynamic__AEBA_NAEAVBlockSource__AEBVBlockPos__AEAVRandom___N_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x16C9CD0));
	_switchBlock_BlockPalette__QEBAAEBVBlock__AEBV2_AEBVBlockLegacy___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1776150));
	_isInstanceOf_ActorClassTree__SA_NAEBVActor__W4ActorType___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1292570));
	_getVariant_Actor__QEBAHXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1260230));
	_setVariant_Actor__QEAAXH_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1260270));
	_isPersistent_Actor__QEBA_NXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x127F050));
	_setPersistent_Actor__QEAAXXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1261300));
	_getStatusFlag_Actor__QEBA_NW4ActorFlags___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1271B50));
	_setStatusFlag_Actor__QEAA_NW4ActorFlags___N_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1271BC0));
	_addEffect_Actor__QEAAXAEBVMobEffectInstance___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1277630));
	__0MobEffectInstance__QEAA_IHHHHH_N00_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x14E54B0));
	_getByName_MobEffect__SAPEAV1_AEBV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x14E2F50));
	_get_I18n__SA_AV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEBV23__Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x0FD6BF0));
	__takeLiquid_BucketItem__QEBA_NAEAVItemStack__AEAVActor__AEBVBlockPos___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x151BA00));
	_ejectItem_DispenserBlock__SAXAEAVBlockSource__AEBVVec3__EAEBVItemStack___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x16A6F40));
	__0ItemSpriteRenderer__QEAA_AEAVTextureGroup_mce__PEAVItem___N_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x0983AB0));
	__1ItemSpriteRenderer__UEAA_XZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x0983BC0));
	_onAppSuspended_ItemSpriteRenderer__UEAAXXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x0983D50));
	__renderQuad_ItemSpriteRenderer__QEAAXAEAVBaseActorRenderContext__AEAVActor__AEAVMesh_mce__AEBVVec3__MM_Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x0984220));
	__buildQuad_ItemSpriteRenderer__QEAAXAEAVBaseActorRenderContext__AEAVActor__AEAVMesh_mce___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x0983EB0));
	__1Mesh_mce__QEAA_XZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x0DD3F60));
	__0Mesh_mce__QEAA_XZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x0DD3D80));
	_reset_Mesh_mce__QEAAXXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x0DD4500));
	_isValid_Mesh_mce__QEBA_NXZ_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0xDD47B0));
	_init_Recipes__QEAAXAEAVResourcePackManager___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x152D6D0));
	_addFurnaceRecipeAuxData_Recipes__QEAAXAEBVItemInstance__0AEBV_$vector_VHashString_Util__V_$allocator_VHashString_Util___std___std___Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x15392B0));
	_addShapedRecipe_Recipes__QEAAXV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEBVItemInstance__AEBV23_22AEBV_$vector_VType_Recipes__V_$allocator_VType_Recipes___std___3_AEBV_$vector_VHashString_Util__V_$allocator_VHashString_Util___std___3_HV_$function_$$A6A_AV_$unique_ptr_VShapedRecipe__U_$default_delete_VShapedRecipe___std___std__V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__2_HHAEBV_$vector_VRecipeIngredient__V_$allocator_VRecipeIngredient___std___2_AEBV_$vector_VItemInstance__V_$allocator_VItemInstance___std___2_VHashString_Util___Z_3__Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x153A270));
	_addShapedRecipe_Recipes__QEAAXV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEBVItemInstance__AEBV23_2AEBV_$vector_VType_Recipes__V_$allocator_VType_Recipes___std___3_AEBV_$vector_VHashString_Util__V_$allocator_VHashString_Util___std___3_HV_$function_$$A6A_AV_$unique_ptr_VShapedRecipe__U_$default_delete_VShapedRecipe___std___std__V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__2_HHAEBV_$vector_VRecipeIngredient__V_$allocator_VRecipeIngredient___std___2_AEBV_$vector_VItemInstance__V_$allocator_VItemInstance___std___2_VHashString_Util___Z_3__Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x153A090));
	_addShapedRecipe_Recipes__QEAAXV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEBVItemInstance__AEBV23_AEBV_$vector_VType_Recipes__V_$allocator_VType_Recipes___std___3_AEBV_$vector_VHashString_Util__V_$allocator_VHashString_Util___std___3_HV_$function_$$A6A_AV_$unique_ptr_VShapedRecipe__U_$default_delete_VShapedRecipe___std___std__V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__2_HHAEBV_$vector_VRecipeIngredient__V_$allocator_VRecipeIngredient___std___2_AEBV_$vector_VItemInstance__V_$allocator_VItemInstance___std___2_VHashString_Util___Z_3__Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1539F00));
	_addShapedRecipe_Recipes__QEAAXV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEBVItemInstance__AEBV_$vector_V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__V_$allocator_V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___2__3_AEBV_$vector_VType_Recipes__V_$allocator_VType_Recipes___std___3_AEBV_$vector_VHashString_Util__V_$allocator_VHashString_Util___std___3_HV_$function_$$A6A_AV_$unique_ptr_VShapedRecipe__U_$default_delete_VShapedRecipe___std___std__V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__2_HHAEBV_$vector_VRecipeIngredient__V_$allocator_VRecipeIngredient___std___2_AEBV_$vector_VItemInstance__V_$allocator_VItemInstance___std___2_VHashString_Util___Z_3__Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x1539D90));
	_addShapedRecipe_Recipes__QEAAXV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__AEBV_$vector_VItemInstance__V_$allocator_VItemInstance___std___3_AEBV_$vector_V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__V_$allocator_V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std___2__3_AEBV_$vector_VType_Recipes__V_$allocator_VType_Recipes___std___3_AEBV_$vector_VHashString_Util__V_$allocator_VHashString_Util___std___3_HV_$function_$$A6A_AV_$unique_ptr_VShapedRecipe__U_$default_delete_VShapedRecipe___std___std__V_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__2_HHAEBV_$vector_VRecipeIngredient__V_$allocator_VRecipeIngredient___std___2_AEBV_$vector_VItemInstance__V_$allocator_VItemInstance___std___2_VHashString_Util___Z_3__Z_ptr = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x15394D0));
	Item_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2B766C0));
	DiggerItem_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2B72240));
	BlockPlanterItem_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2B6F570));
	BlockItem_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2B6F258));
	BucketItem_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2B701D0));
	BlockLegacy_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2B8E7D0));
	LiquidBlock_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2BAE780));
	HeavyBlock_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2BA8488));
	ItemInstance_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2B769D8));
	ItemStack_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2B76AD8));
	Actor_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2B14130));
	Mob_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2B442F0));
	Player_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2B59C90));
	Monster_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2B4C488));
	Slime_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2B51040));
	Throwable_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2B60730));
	Container_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2B64268));
	Level_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2BCF460));
	ItemSpriteRenderer_vtable = reinterpret_cast<void*>(Zenova::Hook::SlideAddress(0x2AC98E0));
}

#include <Windows.h>

BOOL APIENTRY DllMain(HMODULE hModule, DWORD fdwReason, LPVOID lpReserved) {
	if(fdwReason == DLL_PROCESS_ATTACH) InitBedrockPointers();
	return TRUE;
}
